// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package sqlc

import (
	"context"
)

const getArtist = `-- name: GetArtist :one
SELECT id, name, social_profiles, created_at, updated_at, deleted_at FROM artists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArtist(ctx context.Context, id int64) (Artists, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i Artists
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocialProfiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertArtist = `-- name: InsertArtist :one
INSERT INTO artists (
  name, social_profiles
) VALUES (
  $1, $2
)
RETURNING id, name, social_profiles, created_at, updated_at, deleted_at
`

type InsertArtistParams struct {
	Name           string `json:"name"`
	SocialProfiles []byte `json:"social_profiles"`
}

func (q *Queries) InsertArtist(ctx context.Context, arg InsertArtistParams) (Artists, error) {
	row := q.db.QueryRow(ctx, insertArtist, arg.Name, arg.SocialProfiles)
	var i Artists
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocialProfiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
