// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artworks.sql

package sqlc

import (
	"context"
)

const findByHash = `-- name: FindByHash :one
SELECT id, title, file_path, source_url, p_hash, meta_data, artist_id, created_at, updated_at, deleted_at FROM artworks
WHERE p_hash = $1 LIMIT 1
`

func (q *Queries) FindByHash(ctx context.Context, pHash string) (Artworks, error) {
	row := q.db.QueryRow(ctx, findByHash, pHash)
	var i Artworks
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.SourceUrl,
		&i.PHash,
		&i.MetaData,
		&i.ArtistID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertArtwork = `-- name: InsertArtwork :one
INSERT INTO artworks (
  title, file_path, source_url, p_hash, meta_data, artist_id
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, title, file_path, source_url, p_hash, meta_data, artist_id, created_at, updated_at, deleted_at
`

type InsertArtworkParams struct {
	Title     string `json:"title"`
	FilePath  string `json:"file_path"`
	SourceUrl string `json:"source_url"`
	PHash     string `json:"p_hash"`
	MetaData  []byte `json:"meta_data"`
	ArtistID  int64  `json:"artist_id"`
}

func (q *Queries) InsertArtwork(ctx context.Context, arg InsertArtworkParams) (Artworks, error) {
	row := q.db.QueryRow(ctx, insertArtwork,
		arg.Title,
		arg.FilePath,
		arg.SourceUrl,
		arg.PHash,
		arg.MetaData,
		arg.ArtistID,
	)
	var i Artworks
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.SourceUrl,
		&i.PHash,
		&i.MetaData,
		&i.ArtistID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listArtworksByArtist = `-- name: ListArtworksByArtist :many
SELECT id, title, file_path, source_url, p_hash, meta_data, artist_id, created_at, updated_at, deleted_at FROM artworks
WHERE artist_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListArtworksByArtist(ctx context.Context, artistID int64) ([]Artworks, error) {
	rows, err := q.db.Query(ctx, listArtworksByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artworks
	for rows.Next() {
		var i Artworks
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.SourceUrl,
			&i.PHash,
			&i.MetaData,
			&i.ArtistID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtworkMetadata = `-- name: UpdateArtworkMetadata :exec
UPDATE artworks
SET meta_data = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateArtworkMetadataParams struct {
	ID       int64  `json:"id"`
	MetaData []byte `json:"meta_data"`
}

func (q *Queries) UpdateArtworkMetadata(ctx context.Context, arg UpdateArtworkMetadataParams) error {
	_, err := q.db.Exec(ctx, updateArtworkMetadata, arg.ID, arg.MetaData)
	return err
}
