// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID             int64
	Name           string
	SocialProfiles []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Artwork struct {
	ID        int64
	Title     string
	FilePath  string
	SourceUrl string
	PHash     string
	MetaData  []byte
	ArtistID  int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type ArtworkTag struct {
	ArtworkID int64
	TagID     int64
}

type Tag struct {
	ID        int64
	Name      string
	Category  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type User struct {
	ID        int64
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
