// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artists struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	SocialProfiles []byte             `json:"social_profiles"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type ArtworkTags struct {
	ArtworkID int64 `json:"artwork_id"`
	TagID     int64 `json:"tag_id"`
}

type Artworks struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	FilePath  string             `json:"file_path"`
	SourceUrl string             `json:"source_url"`
	PHash     string             `json:"p_hash"`
	MetaData  []byte             `json:"meta_data"`
	ArtistID  int64              `json:"artist_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Tags struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Category  string             `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Users struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
