// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	FindByHash(ctx context.Context, pHash string) (Artworks, error)
	GetArtist(ctx context.Context, id int64) (Artists, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id int64) (Users, error)
	InsertArtist(ctx context.Context, arg InsertArtistParams) (Artists, error)
	InsertArtwork(ctx context.Context, arg InsertArtworkParams) (Artworks, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (Users, error)
	ListArtworksByArtist(ctx context.Context, artistID int64) ([]Artworks, error)
	UpdateArtworkMetadata(ctx context.Context, arg UpdateArtworkMetadataParams) error
}

var _ Querier = (*Queries)(nil)
