// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uwwwwoooooooh/daily-uwoh/internal/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination internal/db/mock/store.go github.com/uwwwwoooooooh/daily-uwoh/internal/db/sqlc Store
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/uwwwwoooooooh/daily-uwoh/internal/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// FindByHash mocks base method.
func (m *MockStore) FindByHash(ctx context.Context, pHash string) (sqlc.Artworks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, pHash)
	ret0, _ := ret[0].(sqlc.Artworks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockStoreMockRecorder) FindByHash(ctx, pHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockStore)(nil).FindByHash), ctx, pHash)
}

// GetArtist mocks base method.
func (m *MockStore) GetArtist(ctx context.Context, id int64) (sqlc.Artists, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtist", ctx, id)
	ret0, _ := ret[0].(sqlc.Artists)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtist indicates an expected call of GetArtist.
func (mr *MockStoreMockRecorder) GetArtist(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtist", reflect.TypeOf((*MockStore)(nil).GetArtist), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(ctx context.Context, email string) (sqlc.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(sqlc.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockStore) GetUserByID(ctx context.Context, id int64) (sqlc.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStoreMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStore)(nil).GetUserByID), ctx, id)
}

// InsertArtist mocks base method.
func (m *MockStore) InsertArtist(ctx context.Context, arg sqlc.InsertArtistParams) (sqlc.Artists, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertArtist", ctx, arg)
	ret0, _ := ret[0].(sqlc.Artists)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertArtist indicates an expected call of InsertArtist.
func (mr *MockStoreMockRecorder) InsertArtist(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertArtist", reflect.TypeOf((*MockStore)(nil).InsertArtist), ctx, arg)
}

// InsertArtwork mocks base method.
func (m *MockStore) InsertArtwork(ctx context.Context, arg sqlc.InsertArtworkParams) (sqlc.Artworks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertArtwork", ctx, arg)
	ret0, _ := ret[0].(sqlc.Artworks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertArtwork indicates an expected call of InsertArtwork.
func (mr *MockStoreMockRecorder) InsertArtwork(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertArtwork", reflect.TypeOf((*MockStore)(nil).InsertArtwork), ctx, arg)
}

// InsertUser mocks base method.
func (m *MockStore) InsertUser(ctx context.Context, arg sqlc.InsertUserParams) (sqlc.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", ctx, arg)
	ret0, _ := ret[0].(sqlc.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertUser indicates an expected call of InsertUser.
func (mr *MockStoreMockRecorder) InsertUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockStore)(nil).InsertUser), ctx, arg)
}

// ListArtworksByArtist mocks base method.
func (m *MockStore) ListArtworksByArtist(ctx context.Context, artistID int64) ([]sqlc.Artworks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArtworksByArtist", ctx, artistID)
	ret0, _ := ret[0].([]sqlc.Artworks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArtworksByArtist indicates an expected call of ListArtworksByArtist.
func (mr *MockStoreMockRecorder) ListArtworksByArtist(ctx, artistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArtworksByArtist", reflect.TypeOf((*MockStore)(nil).ListArtworksByArtist), ctx, artistID)
}

// UpdateArtworkMetadata mocks base method.
func (m *MockStore) UpdateArtworkMetadata(ctx context.Context, arg sqlc.UpdateArtworkMetadataParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArtworkMetadata", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateArtworkMetadata indicates an expected call of UpdateArtworkMetadata.
func (mr *MockStoreMockRecorder) UpdateArtworkMetadata(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArtworkMetadata", reflect.TypeOf((*MockStore)(nil).UpdateArtworkMetadata), ctx, arg)
}
