// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const findByHash = `-- name: FindByHash :one
SELECT id, title, file_path, source_url, p_hash, meta_data, artist_id, created_at, updated_at, deleted_at FROM artworks
WHERE p_hash = $1 LIMIT 1
`

func (q *Queries) FindByHash(ctx context.Context, pHash string) (Artwork, error) {
	row := q.db.QueryRow(ctx, findByHash, pHash)
	var i Artwork
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.SourceUrl,
		&i.PHash,
		&i.MetaData,
		&i.ArtistID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArtist = `-- name: GetArtist :one
SELECT id, name, social_profiles, created_at, updated_at, deleted_at FROM artists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArtist(ctx context.Context, id int64) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocialProfiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertArtist = `-- name: InsertArtist :one
INSERT INTO artists (
  name, social_profiles
) VALUES (
  $1, $2
)
RETURNING id, name, social_profiles, created_at, updated_at, deleted_at
`

type InsertArtistParams struct {
	Name           string
	SocialProfiles []byte
}

func (q *Queries) InsertArtist(ctx context.Context, arg InsertArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, insertArtist, arg.Name, arg.SocialProfiles)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocialProfiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertArtwork = `-- name: InsertArtwork :one
INSERT INTO artworks (
  title, file_path, source_url, p_hash, meta_data, artist_id
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, title, file_path, source_url, p_hash, meta_data, artist_id, created_at, updated_at, deleted_at
`

type InsertArtworkParams struct {
	Title     string
	FilePath  string
	SourceUrl string
	PHash     string
	MetaData  []byte
	ArtistID  int64
}

func (q *Queries) InsertArtwork(ctx context.Context, arg InsertArtworkParams) (Artwork, error) {
	row := q.db.QueryRow(ctx, insertArtwork,
		arg.Title,
		arg.FilePath,
		arg.SourceUrl,
		arg.PHash,
		arg.MetaData,
		arg.ArtistID,
	)
	var i Artwork
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.SourceUrl,
		&i.PHash,
		&i.MetaData,
		&i.ArtistID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
  email, password
) VALUES (
  $1, $2
)
RETURNING id, email, password, created_at, updated_at
`

type InsertUserParams struct {
	Email    string
	Password string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtworksByArtist = `-- name: ListArtworksByArtist :many
SELECT id, title, file_path, source_url, p_hash, meta_data, artist_id, created_at, updated_at, deleted_at FROM artworks
WHERE artist_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListArtworksByArtist(ctx context.Context, artistID int64) ([]Artwork, error) {
	rows, err := q.db.Query(ctx, listArtworksByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artwork
	for rows.Next() {
		var i Artwork
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.SourceUrl,
			&i.PHash,
			&i.MetaData,
			&i.ArtistID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtworkMetadata = `-- name: UpdateArtworkMetadata :exec
UPDATE artworks
SET meta_data = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateArtworkMetadataParams struct {
	ID       int64
	MetaData []byte
}

func (q *Queries) UpdateArtworkMetadata(ctx context.Context, arg UpdateArtworkMetadataParams) error {
	_, err := q.db.Exec(ctx, updateArtworkMetadata, arg.ID, arg.MetaData)
	return err
}
